import Head from 'next/head';
import Link from 'next/link';
import HeaderLink from '../components/HeaderLink';
import LogoutIcon from '@mui/icons-material/Logout';
import LoginIcon from '@mui/icons-material/Login';
import AppRegistrationIcon from '@mui/icons-material/AppRegistration';

function Home() {
	return (
		<>
			<Head>
				<title>Home</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
			</Head>
			<header className="flex justify-around items-center py-4">
				<div className="w-36 h-10">Pizza</div>
				<div className="flex items-center sm:divide-x divide-red-600">
					<div className="hidden sm:flex space-x-8 pr-4">
						<HeaderLink Icon={LoginIcon} text="Login" />
						<HeaderLink Icon={LogoutIcon} text="Logout" />
						<Link href="/">
							<a>
								<HeaderLink
									Icon={AppRegistrationIcon}
									text="Dashboard"
								/>
							</a>
						</Link>
					</div>
				</div>
			</header>
		</>
	);
}

export default Home;
